# Piuscyber P3.3 PRO MAX - PDF Threat Report + Map
import socket, threading, requests, os
from datetime import datetime
import tkinter as tk
from tkinter import ttk

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    HAS_PDF = True
except:
    HAS_PDF = False

CAM_PORTS = [80,81,82,83,84,88,8000,8080,8081,8090,554,1935,8554,5000,7001,9000,37777]
THREAT_DB = {80:"HTTP Cam",81:"Alt HTTP",554:"RTSP Stream",8080:"IP Cam Panel",37777:"Dahua DVR",8000:"NVR",9000:"Cam Panel"}

def get_ip_info():
    try:
        local = socket.gethostbyname(socket.gethostname())
    except:
        local = "127.0.0.1"
    try:
        pub = requests.get("https://api.ipify.org", timeout=5).text
        loc = requests.get(f"http://ip-api.com/json/{pub}", timeout=5).json()
        city = f"{loc.get('city')}, {loc.get('country')} ({loc.get('isp')})"
    except:
        pub = "No Internet"
        city = "Unknown"
    return local, pub, city

def generate_pdf(target, open_ports, local, public, location):
    filename = f"Piuscyber_P3.3_Report_{target.replace('.','_')}.pdf"
    if not HAS_PDF:
        with open(filename.replace('.pdf','.txt'), 'w') as f:
            f.write(f"Target: {target}\nOpen: {open_ports}\n")
        return filename.replace('.pdf','.txt')

    c = canvas.Canvas(filename, pagesize=letter)
    c.setFont("Helvetica-Bold", 18)
    c.setFillColorRGB(1,0.5,0)
    c.drawString(50, 750, "Piuscyber P3.3 - Threat Intelligence Report")
    c.setFillColorRGB(0,0,0)
    c.setFont("Helvetica", 11)
    c.drawString(50, 730, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(50, 715, f"Analyst: Piuscyber - Ado-Ekiti, Ekiti State")
    c.drawString(50, 700, f"Local IP: {local} | Public IP: {public}")
    c.drawString(50, 685, f"Location Intel: {location}")
    c.drawString(50, 670, f"Target Scanned: {target}")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, 640, "--- SCAN RESULTS ---")
    c.setFont("Helvetica", 11)
    y = 620
    if open_ports:
        c.setFillColorRGB(1,0,0)
        c.drawString(50, y, f"STATUS: 🚨 EXPOSED - {len(open_ports)} camera ports open!")
        y -= 20
        for p in open_ports:
            c.drawString(70, y, f"Port {p}: {THREAT_DB.get(p,'Unknown Cam')} - HIGH RISK")
            y -= 15
    else:
        c.setFillColorRGB(0,0.6,0)
        c.drawString(50, y, "STATUS: ✅ SECURE - No camera exposure found")
        y -= 20
        c.setFillColorRGB(0,0,0)
        c.drawString(50, y, "All 17 common camera ports are CLOSED")

    c.setFillColorRGB(0,0,0)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(50, 400, "Recommendation:")
    c.setFont("Helvetica", 10)
    c.drawString(50, 385, "1. Keep firewall enabled, 2. Change default camera passwords, 3. Disable UPnP on router")
    c.drawString(50, 370, "4. Regular scan with Piuscyber P3.3 PRO")

    c.setFont("Helvetica-Bold", 9)
    c.drawString(50, 50, "Generated by Piuscyber P3.3 PRO MAX - github.com/piuscyber/piuscyber-p3.0-pro")
    c.save()
    return filename

def start_scan():
    target = ip_entry.get().strip()
    if not target:
        return
    btn.config(state='disabled')
    log.delete(1.0, tk.END)
    log.insert(tk.END, f"[P3.3] Scanning {target}...\n")

    def run():
        open_ports = []
        for port in CAM_PORTS:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.settimeout(0.6)
            try:
                s.connect((target, port))
                log.insert(tk.END, f"[OPEN] {port} - {THREAT_DB.get(port,'CAM')}\n")
                open_ports.append(port)
            except:
                log.insert(tk.END, f"[closed] {port}\n")
            s.close()
            log.see(tk.END)

        pdf_file = generate_pdf(target, open_ports, LOCAL, PUBLIC, LOCATION)
        log.insert(tk.END, f"\n✅ REPORT GENERATED: {pdf_file}\n")
        log.insert(tk.END, "Open the PDF - Na client-ready report be that!\n")
        btn.config(state='normal')

    threading.Thread(target=run, daemon=True).start()

# GUI
LOCAL, PUBLIC, LOCATION = get_ip_info()
root = tk.Tk()
root.title("Piuscyber P3.3 PRO MAX - PDF Report")
root.geometry("700x620")

tk.Label(root, text="Piuscyber P3.3 - PDF Threat Report Generator", font=("Arial",14,"bold"), bg="black", fg="orange").pack(fill=tk.X, pady=5)
tk.Label(root, text=f"{LOCAL} | {PUBLIC} | {LOCATION}", font=("Arial",8)).pack()

f = tk.Frame(root)
f.pack(pady=8)
tk.Label(f, text="Target IP:").pack(side=tk.LEFT)
ip_entry = tk.Entry(f, width=28, font=("Arial",11))
ip_entry.insert(0, PUBLIC)
ip_entry.pack(side=tk.LEFT, padx=5)
ttk.Button(f, text="Use Local", command=lambda: [ip_entry.delete(0,tk.END), ip_entry.insert(0,LOCAL)]).pack(side=tk.LEFT)

btn = tk.Button(root, text="GENERATE PDF REPORT - P3.3 PRO", bg="orange", fg="black", font=("Arial",12,"bold"), command=start_scan)
btn.pack(pady=10)

log = tk.Text(root, height=28, bg="black", fg="#00FF00", font=("Consolas",9))
log.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

root.mainloop()